version: '3'
services:
  nginx:
    image: nginx:latest
    working_dir: /var/www/html
    ports:
      - "${APP_PORT}:443"
    links:
      - db:${APP_URL}
      - fpm
    volumes:
      - ./etc/nginx/conf.d:/etc/nginx/conf.d:cached
      - ./etc/nginx/ssl:/etc/nginx/ssl:cached
      - ./.:/var/www/html:cached

  fpm:
    image: catchdigital/php:7.1.10-fpm
    user: www-data:www-data
    expose:
      - 9000
    links:
      - db:${APP_URL}
    volumes:
      - ./etc/php/config.ini:/usr/local/etc/php/conf.d/x-config.ini:cached
      - ./.:/var/www/html:cached

  db:
    image: percona:5.7
    env_file: .env
    ports:
      - "3306:3306"
    volumes:
       - drucker-db:/var/lib/mysql
       - ./etc/mysql/conf.d:/etc/mysql/conf.d:cached
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}

#  node-sass:
#    image: abesiyo/node-sass:latest
#    command: bash -c "npm install && npm run build"
#    working_dir: /var/www/html/docroot/${PATH_THEME}
#    volumes:
#      - ./.:/var/www/html

volumes:
  drucker-db:

#  composer:
#    image: composer:latest
#    command: install --ignore-platform-reqs --no-scripts
#    working_dir: /var/www/html
#    volumes:
#      - ./.:/var/www/html
